//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyRobot.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FailureMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailureMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToyRobot.Common.Resources.FailureMessages", typeof(FailureMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a command!.
        /// </summary>
        public static string EmptyOrNullCommand {
            get {
                return ResourceManager.GetString("EmptyOrNullCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Compass Direction - valid direction is either NORTH, SOUTH, EAST or WEST.
        /// </summary>
        public static string InvalidCompassDirectionCommand {
            get {
                return ResourceManager.GetString("InvalidCompassDirectionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Direction - valid direction is either RIGHT or LEFT.
        /// </summary>
        public static string InvalidDirectionCommand {
            get {
                return ResourceManager.GetString("InvalidDirectionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First command must be PLACE with DIRECTION.
        /// </summary>
        public static string InvalidFirstCommand {
            get {
                return ResourceManager.GetString("InvalidFirstCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PLACE command - valid game play is between 0 and 6..
        /// </summary>
        public static string InvalidPlaceCommand {
            get {
                return ResourceManager.GetString("InvalidPlaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid REPORT command - enter REPORT to successfully submit commands..
        /// </summary>
        public static string InvalidReportCommand {
            get {
                return ResourceManager.GetString("InvalidReportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Your Toy Robot has fallen! Enter RESTART to start a new game..
        /// </summary>
        public static string ToyRobotOutOfBounds {
            get {
                return ResourceManager.GetString("ToyRobotOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The Toy Robot will fall off the table if moved any further! To get back into the game, provide valid PLACE commands..
        /// </summary>
        public static string ToyRobotOutOfBoundsWarning {
            get {
                return ResourceManager.GetString("ToyRobotOutOfBoundsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command entered, please try again..
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
